version: '3.8'

services:
  db:
    container_name: pg_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: entranceprep
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  entranceprep-backend:
    container_name: entranceprep-backend
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./:/app
      - entranceprep_node-modules:/app/node_modules
    env_file:
      - .env
  
volumes:
  postgres-data:
  entranceprep_node-modules: